language: elixir
elixir:
  - 1.5.3
  - 1.6.4
otp_release:
  - 20.1
  - 19.3
before_script:
  - MIX_ENV=test mix compile --warnings-as-errors
script:
  - MIX_ENV=test mix test
cache:
  directories:
    - _build
    - deps
